name: CI/CD Pipeline
 
on:
  push
 
jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run Build Commands
        run: |
          echo "Building the project..."
          echo "Build complete" > build.log
          cat build.log
 
  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "All tests passed!" > test.log
          cat test.log
 
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run Deployment
        run: |
          echo "Deploying application..."
          echo "Deployment successful!" > deploy.log
          cat deploy.log