name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

jobs:
  # Job 1: Build and Prepare
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step (if needed)
        run: |
          echo "You can compile, bundle, or optimize here if needed"
          ls -l  # View files for confirmation

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site-files
          path: .  # Upload everything (customize if needed)

  # Job 2: Deploy to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Run only after build job completes

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: site-files

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: azweb  # Your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .  # This deploys the downloaded files
