name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Deploy on push to the main branch (change if using a different branch)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (Optional if you have other build steps)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose the appropriate Node version (if needed for other steps)
        
      # Step 3: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: azweb  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .  # The root directory for deployment

          
