name: PR Title Validation

on:
  pull_request:
    types: [opened]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title starts with "github"
        uses: actions/github-script@v7
        env:
          TITLE: ${{ github.event.pull_request.title }}
        with:
          script: |
            const title = process.env.TITLE;
            const pattern = /^github/i;  // case-insensitive match for "github" at the start

            if (!pattern.test(title)) {
              core.setFailed(" PR title must start with 'github'. Example: 'github: fix workflow'");
            } else {
              console.log(" PR title format is valid.");
            }
